### PR TITLE
Allow user to update Who You Are 

### LINKED ISSUE #58: Update who are you pop up to display current user details

### PR DESCRIPTION
**Pull request by katzyx**
The Who You Are pop-up has been updated to allow the user to combine their current description with new information as shown below. Previously, the new user details would overwrite the existing details. 

The pop-up has been converted a side bar for more space.

The blog post and product recommendations are updated to reflect these changes

Closes #58

image

### CODE REVIEW

**Review by hopehadfield — CHANGES_REQUESTED** [review]
Screenshot 2024-11-28 at 4 09 06 PM
This is what shows up when I first open the sidebar. Once I update the description and re-open the sidebar, it shows up properly (with the describe prompt).

**Comment by hopehadfield** [comment]
Also the preview can get a little bit weird and unnecessary.. maybe we should hold off on adding this? i.e. when I entered that I was a 21 year old woman with clear skin, it said "Meet a 21 year old woman with clear skin, ready to take on the world!"

**Comment by maiseyperelonia** [comment]
> Also the preview can get a little bit weird and unnecessary.. maybe we should hold off on adding this? i.e. when I entered that I was a 21 year old woman with clear skin, it said "Meet a 21 year old woman with clear skin, ready to take on the world!"

IM LAUGHING

**Comment by katzyx** [comment]
> Also the preview can get a little bit weird and unnecessary.. maybe we should hold off on adding this? i.e. when I entered that I was a 21 year old woman with clear skin, it said "Meet a 21 year old woman with clear skin, ready to take on the world!"

Unfortunately this isn't a problem with the preview, it'll be saved as that if we want to combine the user's new and previous info. I can edit the prompt to nothing unnecessary is added. We can hold off on this PR until it's well tested.

**Review by hopehadfield — APPROVED** [review]
LGTM

**Pull request merged**
