### PR TITLE
Enhance readability of blog post

### PR DESCRIPTION
**Pull request by katzyx**
Left aligned text with bullet points (max 6 sentences) instead of a wall of text, and added a border to help it stand out from the products

image

### CODE REVIEW

**Review by hopehadfield — COMMENTED** [review]
The last sentence consistently has a double period, not sure if this is the return from ChatGPT or a formatting issue?

Also, I think I prefer the white background. Not sure what @floriafz23 and @maiseyperelonia think though.

**Comment by maiseyperelonia** [comment]
formatting-wise, i think there are better ways to separate the info so that it's not just one sentence per bullet point

**Comment by katzyx** [comment]
> formatting-wise, i think there are better ways to separate the info so that it's not just one sentence per bullet point

is there something you would like to suggest?

**Comment by maiseyperelonia** [comment]
i think we can add more specification on how the gpt output should be formatted- although it will clearly look like it was ai-generated

**Comment by katzyx** [comment]
I added an error check for parsing the price in this PR because I wasn't able to test my code without it

**Comment by hopehadfield** [comment]
Looks good visually but I got this warning:

SyntaxWarning: invalid escape sequence '\d'
price_string = re.sub("[^\d\.]", "", element)

**Review by floriafz23 — APPROVED** [review]
lgtm

**Pull request merged**
